name: TestUnit
on: [pull_request]

jobs:
  test-unit:
    name: Test Units
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Run unit tests
        run: sudo sh -c "make test-integration"
